version: '3.3'
services:
        localtunnel:
                image: source-localtunnel-server:1.0.0
                build: .
                restart: always
                network_mode: 'host'
                command: '-s true -p 7001 -d lt.beebeebeeebeee.com --4r "https://beebeebeeebeee.com/404"'
                #logging:
                        #driver: "syslog"
